title: njoverton
url: "https://njoverton.com/"
baseurl: "/"
# Permalink configuration
permalink: /:title/

# Ensure posts are processed
future: true
# Base URL (important if you're hosting on GitHub Pages)
baseurl: ""

# Site URL (if different from baseurl)
url: ""


markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/njoverton"
footer_text: "Terms and conditions apply."

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "pinboard"
   link: "/pinboard/"
 - name: "guestbook"
   link: "/guestbook/"
 - name: "about"
   link: "/about/"
